#ifdef CONFIG_SMP
#define CONFIG_NR_CPUS 8
#else
#define CONFIG_NR_CPUS 1
#endif

#undef CONFIG_TRACE_BRANCH_PROFILING
//Needs generated header:
#undef CONFIG_ACPI_CUSTOM_DSDT
//Is always false on x86 even if defined:
#undef CONFIG_SBUS


#define AUTOCONF_INCLUDED
#define CONFIG_FRAME_WARN 1024
#define CONFIG_ARCH_DEFCONFIG "arch/x86/configs/i386_defconfig"
#define CONFIG_RCU_FANOUT 32
#define CONFIG_OUTPUT_FORMAT "elf32-i386"
#define CONFIG_DEFCONFIG_LIST "/lib/modules/$UNAME_RELEASE/.config"
#define CONFIG_PHYSICAL_ALIGN 0x1000000
#define CONFIG_IO_DELAY_TYPE_UDELAY 2
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_X86_L1_CACHE_SHIFT 5
#define CONFIG_EXTRA_FIRMWARE ""
#define CONFIG_PAGE_OFFSET 0xC0000000
#define CONFIG_PHYSICAL_START 0x1000000
#define CONFIG_DEFAULT_MMAP_MIN_ADDR 4096
#define CONFIG_SPLIT_PTLOCK_CPUS 4
#define CONFIG_IO_DELAY_TYPE_0X80 0
#define CONFIG_IO_DELAY_TYPE_0XED 1
#define CONFIG_ILLEGAL_POINTER_VALUE 0x0
#define CONFIG_X86_INTERNODE_CACHE_SHIFT 5
#define CONFIG_DEFAULT_IOSCHED "noop"
#define CONFIG_DEFAULT_IO_DELAY_TYPE 0
#define CONFIG_UEVENT_HELPER_PATH "/sbin/hotplug"
#define CONFIG_LOCALVERSION ""
#define CONFIG_INIT_ENV_ARG_LIMIT 32
#define CONFIG_IO_DELAY_TYPE_NONE 3
#define CONFIG_HZ 250
#define CONFIG_X86_MINIMUM_CPU_FAMILY 5
#define CONFIG_DEFAULT_SECURITY ""
#define CONFIG_BASE_SMALL 0
#define CONFIG_LOG_BUF_SHIFT 17

#define KBUILD_STR(s) #s
